#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Dec 17, 2021 11:46:39 AM CET  platform: Linux

import sys
from tkinter import Radiobutton
from typing import Text
from matplotlib.pyplot import text

from numpy.lib.function_base import insert, select
import Anritsu_MS2830A as SPA
import Utils
from tabs import measure_tab, configuration_tab, connect_tab

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
import gui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = UserInterface (root)
    gui_support.init(root, top)
    root.mainloop()

w = None
def create_UserInterface(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_UserInterface(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel(root)
    top = UserInterface(w)
    gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_UserInterface():
    global w
    w.destroy()
    w = None

class UserInterface:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x736+308+141")
        top.minsize(1, 1)
        top.maxsize(3825, 2130)
        top.resizable(1,  1)
        top.title("Multifeed receiver measure")

        #############################
        # ANRITSU CONFIGURATION
        #############################
        config_interface = Utils.read_config_file("../config/config_interface.json")
        config_file = Utils.read_config_file("../config/config_MS2830A.json")
        ##############################

        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
            [('selected', _compcolor), ('active',_ana2color)])
        
        #############################
        # NOTEBOOK CREATION
        #############################
        self.TNotebook1 = ttk.Notebook(top)
        self.TNotebook1.place(relx=0.017, rely=0.014, relheight=0.969
                , relwidth=0.953)
        self.TNotebook1.configure(takefocus="")
        self.TNotebook1_t1 = tk.Frame(self.TNotebook1)
        
        #############################
        # TABS CREATION
        #############################
        connect_tab.connect(self, self.TNotebook1, config_interface, config_file)
        configuration_tab.configuration(self, self.TNotebook1, config_interface, config_file)
        measure_tab.measure(self,self.TNotebook1)

if __name__ == '__main__':
    vp_start_gui()





